# Generated by Django 3.2.19 on 2023-09-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sprice', models.FloatField()),
                ('dprice', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField()),
                ('prodapp', models.TextField()),
                ('category', models.TextField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LA', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('IC', 'Icecreams')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
